// records.fields[0].stop_name
let lstArretsC3 = {
    "records": {
        "fields": [
            {"stop_name" : "Bd De Doulon"},
            {"stop_name" : "Prairie De Mauves"},
            {"stop_name" : "San-Francisco"},
            {"stop_name" : "La Roche"},
            {"stop_name" : "Malakoff"},
            {"stop_name" : "Hongrie"},
            {"stop_name" : "Écosse"},
            {"stop_name" : "Haubans"},
            {"stop_name" : "Picasso"},
            {"stop_name" : "Tbilissi"},
            {"stop_name" : "Gare Sud"},
            {"stop_name" : "Lieu Unique"},
            {"stop_name" : "Monteil"},
            {"stop_name" : "Hôtel Dieu"},
            {"stop_name" : "Commerce"},
            {"stop_name" : "St-Nicolas"},
            {"stop_name" : "Copernic"},
            {"stop_name" : "Édit De Nantes"},
            {"stop_name" : "Lamoricière"},
            {"stop_name" : "Canclaux"},
            {"stop_name" : "Lamartine"},
            {"stop_name" : "Littré"},
            {"stop_name" : "Grillaud"},
            {"stop_name" : "Procé"},
            {"stop_name" : "Poincaré"},
            {"stop_name" : "Delacroix"},
            {"stop_name" : "Vincent Auriol"},
            {"stop_name" : "Jean Ingres"},
            {"stop_name" : "Raoul Dufy"},
            {"stop_name" : "Châtaigniers"},
            {"stop_name" : "Maison Blanche"},
            {"stop_name" : "Bd Charles Gautier"},
            {"stop_name" : "Claude Bernard"},
            {"stop_name" : "Duguay Trouin"},
            {"stop_name" : "Franklin"},
            {"stop_name" : "Edith Piaf"},
            {"stop_name" : "Zénith"},
            {"stop_name" : "Armor"}
        ]}
}